# Generated by Django 4.1.4 on 2023-03-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0005_client_password_lawyer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.client')),
            ],
        ),
    ]
