# Generated by Django 4.1.4 on 2023-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_review1_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='document1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='image/')),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
    ]
