# Generated by Django 4.1.4 on 2023-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_document1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document1',
            name='doc',
        ),
        migrations.AddField(
            model_name='document1',
            name='file1',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document1',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
