# Generated by Django 4.1.4 on 2023-03-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_client_password_lawyer_password'),
        ('client', '0005_remove_document1_doc_document1_file1_document1_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='document1',
        ),
        migrations.AddField(
            model_name='review1',
            name='clientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.client'),
            preserve_default=False,
        ),
    ]
