# Generated by Django 4.1.4 on 2023-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_document_delete_document1_review1_clientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotpas1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
