# Generated by Django 4.1.4 on 2023-04-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_client_court'),
        ('client', '0007_forgotpas1'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.client'),
            preserve_default=False,
        ),
    ]
