# Generated by Django 4.1.4 on 2023-02-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50)),
                ('catdisc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='image/')),
                ('category', models.CharField(max_length=30)),
                ('pdetail', models.CharField(max_length=700)),
                ('experience', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('add', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('postalcode', models.IntegerField(max_length=6)),
                ('lawyername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=30)),
                ('casedate', models.DateField()),
                ('catgname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.category')),
                ('clname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.client')),
            ],
        ),
    ]
