# Generated by Django 4.1.4 on 2023-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='img',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
