# Generated by Django 4.1.2 on 2023-02-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_remove_lawyer_img_lawyer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lawname',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='superuser.lawyer'),
            preserve_default=False,
        ),
    ]
