# Generated by Django 4.1.4 on 2023-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_case_lawname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postalcode',
            field=models.IntegerField(),
        ),
    ]
