# Generated by Django 4.1.4 on 2023-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_client_password_lawyer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='court',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
