# Generated by Django 4.1.4 on 2023-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_client_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
