# Generated by Django 4.1.4 on 2023-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0007_lawyer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='court',
        ),
    ]
