# Generated by Django 4.1.4 on 2023-04-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_court_remove_client_court'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='court',
            new_name='court_detail',
        ),
        migrations.AddField(
            model_name='client',
            name='court1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.court_detail'),
            preserve_default=False,
        ),
    ]
