# Generated by Django 4.1.4 on 2023-04-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0009_rename_court_court_detail_client_court1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='court1',
        ),
    ]
