# Generated by Django 4.1.4 on 2023-01-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='msg',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='uid',
            field=models.IntegerField(max_length=9),
        ),
    ]
