# Generated by Django 4.1.4 on 2023-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_review_msg_alter_review_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
