# Generated by Django 4.1.4 on 2023-03-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_review_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
