# Generated by Django 4.1.4 on 2023-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
