# Generated by Django 4.1.4 on 2023-03-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_alter_log_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
