# Generated by Django 4.1.4 on 2023-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotpas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
